.PHONY: clean All

All:
	@echo "----------Building project:[ quadtree - Release ]----------"
	@cd "quadtree" && "$(MAKE)" -f  "quadtree.mk"
clean:
	@echo "----------Cleaning project:[ quadtree - Release ]----------"
	@cd "quadtree" && "$(MAKE)" -f  "quadtree.mk" clean
